Remove crossbeam
realcr/async_mutex pull request #2
Opened 2018-06-06 14:05 UTC by juchiast

Previous pull request is closed due to conflict.

2018-06-06 14:34 UTC, realcr commented on Cargo.toml
> +authors = ["real <real@freedomlayer.org>"]
You should add yourself and Kamyuen Tse (kevin.xjy@gmail.com) as authors. After all you two made this work.

2018-06-06 14:35 UTC, realcr commented
You are fast!

2018-06-06 15:42 UTC, realcr requested changes
You can add yourself and kamx to the authros list (:

2018-06-07 04:05 UTC, juchiast commented
I added me and kamx in 9eaa562.
And solve https://github.com/realcr/async_mutex/issues/5 in 90871c4

2018-06-07 05:45 UTC, realcr commented
Thanks!

2018-06-07 05:45 UTC, merged